### PR TITLE
fix InvalidValueError: not an instance of HTMLInputElement

### PR DESCRIPTION
**Pull request by meyer59**
https://github.com/brandonjbegle/nova4-google-autocomplete-field/issues/3

### CODE REVIEW

**Comment by meyer59** [comment]
Hey @brandonjbegle 
Could you kindly review this PR? It’s currently blocking our Nova functionality.
The issue arises when dealing with large forms in Nova: the HTML element isn't ready, and Google attempts to bind the autocomplete attribute to `null`. This PR addresses the problem by ensuring the binding occurs after `nextTick`, resolving the issue.
Thank you,

**Comment by brandonjbegle** [comment]
@meyer59 I will build this in a bit and then release it.

**Comment by brandonjbegle** [comment]
@meyer59 I built and released to 0.2.4. Please confirm it works as expected.

**Comment by meyer59** [comment]
Still not, there must be another place where a nextTick is needed

**Comment by brandonjbegle** [comment]
@meyer59 How about some kind of setInterval until it is a valid ref, then return and cancel the interval

**Comment by brandonjbegle** [comment]
@meyer59 
If you pull down and install the local package in your project, you should be able to make a dev build of the package and see exactly where the bug is coming from

**Comment by brandonjbegle** [comment]
@meyer59 were you able to fix this internally?

**Comment by meyer59** [comment]
Not really, issue is still here.

**Comment by meyer59** [comment]
Hi @brandonjbegle 
This pr should fix the issue, @franckitho worked on it, Thanks
https://github.com/brandonjbegle/nova4-google-autocomplete-field/pull/8

**Comment by brandonjbegle** [comment]
@meyer59 Thanks, I will take a look this weekend and if everything looks good, I'll merge and release it.

**Pull request merged**
